### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by philthefox** [jpvantassel/cptpy#1]
When trying to run a script using cptpy the following error occurs:

```
ImportError: cannot import name 'CPT' from 'cptpy'
```

I'm using PyCharm (Professional Edition) and imported cptpy using the built-in package function.

I tried to run the following script:

```
import numpy as np
from cptpy.cpt import CPT
from cptpy.cptu import CPTu

depth = []
qc = []
fs = []
u2 = []

cpt = CPT(depth, qc, fs)
cptu = CPTu(depth, qc, fs, u2)
```

**Comment by jpvantassel** [comment]
Hi,
I am not able to reproduce the error above. If you are using an older version of `cptpy`, please update to the latest commit on the main branch.
All the best,
Joe
